### ISSUE TITLE
don't pass nested require...

### ISSUE THREAD

**Issue by tracker1** [typicode/please-upgrade-node#1]
I would think that `require('please-upgrade-node')('./your-package-root')` would be more appropriate, than a nested require, this way the test can run, then the please-upgrade can simply require(...) on its' own.

If you do this, there's no need to restrict syntax availability for the nested package.

**Comment by typicode** [comment]
Good point! Do you want to make a PR?

**Comment by stramel** [comment]
Hm, personally I like the ability to pass in an object

**Comment by tracker1** [comment]
@stramel It could be an object or string, if object, just returns the object, otherwise returns require(INPUT_VALUE)

**Comment by typicode** [comment]
I've created a PR to change the API https://github.com/typicode/please-upgrade-node/pull/3
For the moment, I don't see reasons not to use the package directory instead (maybe there are)?

**Comment by Dan503** [comment]
I'm thinking that it would be possible to avoid having to parse in the package.json entirely.

The folder structure is pretty much always going to look like this:

``````````
[Root]
 - node_modules
 - - please-upgrade-node
 - - - index.js
 - package.json
``````````

If inside index.js you have the following:

``````````
var pkg = require("../../package.json");
``````````

You could then call please-upgrade-node by just doing this in the vast majority of cases:

``````````
require("please-upgrade-node")();
``````````

It should use that by default but people could then override the default by parsing in an object or a string to a package.json that is in a weird location.

**Comment by Dan503** [comment]
Sorry, I meant this folder structure:

````````
[Root]
 - node_modules
 - - please-upgrade-node
 - - - index.js
 - package.json
````````

(I'm on mobile and can't edit. I'll clean it up later and delete this comment)

**Comment by typicode** [comment]
@Dan503 hmm could be very smart, don't know if there would be some edge cases or not.

**Comment by Dan503** [comment]
If there are edge cases, then that is why you would allow people to still parse in a custom package.json object of their own. That would override the default of looking for the typical package.json set up.

This is just how I think the default behavior should act since the folder structure in 99.99% of installs would be identical.

Allowing people to parse in a string is going to be problematic since a relative string in one file will point to a different location than a relative string in another. Allowing the parsing in of strings would surely lead to an avalanche of bugs.

I think my solution gets at the core of the issue in that developers are lazy and want to type as little as possible.

This wouldn't even be a breaking change since all current implementations would simply be using the overide functionality instead of the default functionality.

**Comment by typicode** [comment]
Actually, I've rolled back to the first approach:

```js
#!/usr/bin/env node
const pkg = require('./package.json')
require('please-upgrade-node')(pkg)
```

It's less smart but easier to debug and understand (that's also how they do in https://github.com/yeoman/update-notifier).

I've also (re)discovered that it's possible to use `const` with Node 0.12 (unless you add `use strict;`), so there was no need to have a caveat section actually, the example should work down to 0.12.

Thank you all for the feedbacks and PRs :)
